version: '3'

services:
  django:
    image: python:3.9-alpine
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - pip39:/usr/local/lib/python3.9/site-packages
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db
    working_dir: /project
    command: sh -c "apk add build-base mariadb-dev gcc libc-dev libffi-dev && pip install --upgrade pip && pip install -r requirements.txt && sh migrate.sh && python manage.py runserver 0.0.0.0:8000 --noreload"
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=dormtown
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - "3306"
volumes:
  pip39:
    external: true
