# Generated by Django 4.1.2 on 2022-11-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_service',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='tv_fridge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='wardrobe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='water_heater',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='room_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='occupant.room'),
        ),
    ]
