# Generated by Django 3.2.16 on 2022-11-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='status_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_type', to='occupant.statustype'),
        ),
    ]
