# Generated by Django 3.2.16 on 2022-11-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupant', '0002_roomtype_room_service_roomtype_tv_fridge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_room_type', to='occupant.roomtype'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_id', to='occupant.role'),
        ),
    ]
