# Generated by Django 4.1.2 on 2022-11-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupant', '0003_alter_report_assign_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assign_to_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
