name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          pip3 install --user -r requirements.txt
          pip3 install coverage
          pip3 install livereload
          pip3 install fontawesomefree
          python3 manage.py makemigrations
          python3 manage.py migrate
          coverage run --source='.' manage.py test
          coverage report
